services:
  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
    extends:
      file: ./services/backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/oldUI.Dockerfile
      args:
        RELEASE_VERSION: 8.1.1
    pull_policy: build
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: "https://staging.riselabs.xyz"
      ETHEREUM_JSONRPC_TRACE_URL: "https://staging.riselabs.xyz"
      NFT_MEDIA_HANDLER_ENABLED: "false"
      NFT_MEDIA_HANDLER_REMOTE_DISPATCHER_NODE_MODE_ENABLED: "false"
    ports:
      - "25723:4000"

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend
    environment:
      NEXT_PUBLIC_API_HOST: "${BLOCKSCOUT_PUBLIC_HOST:-localhost}"
      NEXT_PUBLIC_API_PROTOCOL: "http"
      NEXT_PUBLIC_API_PORT: "25723"
      NEXT_PUBLIC_APP_HOST: "${BLOCKSCOUT_PUBLIC_HOST:-localhost}"
      NEXT_PUBLIC_APP_PROTOCOL: http
      NEXT_PUBLIC_APP_PORT: "25743"
      NEXT_PUBLIC_STATS_API_HOST: http://${BLOCKSCOUT_PUBLIC_HOST:-localhost}:25778
      NEXT_PUBLIC_NETWORK_NAME: "RISE Staging"
      NEXT_PUBLIC_NETWORK_SHORT_NAME: "RISE"
    ports:
      - "25743:3000"

  stats-db-init:
    extends:
      file: ./services/stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      stats-db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - backend
    extends:
      file: ./services/stats.yml
      service: stats
    ports:
      - "25778:8050"
    environment:
      STATS__BLOCKSCOUT_API_URL: "http://backend:4000"
      STATS__SERVER__HTTP__CORS__ALLOWED_ORIGIN: "http://${BLOCKSCOUT_PUBLIC_HOST:-localhost}:25743"
      STATS__SERVER__HTTP__CORS__ENABLED: "true"
